#!/usr/bin/fish
#make -f install.mk $argv
function check
    echo $argv
    eval $argv
    set s $status
    if not test $s = 0
	echo not 0
	exit $s
    end
end

function test_not_exist -a dir
    if test ! -e $dir
        return 0
    else
        echo $dir exists!
        return 1
    end
end

function ensure_dir -a dir
    # if not test -e $dir
    #     echo "$dir don't exist, creat it"
    #     mkdir -p $dir
    # end
    test_not_exist $dir
    and check mkdir -p $dir
end

function try_link -a src dist
    # if test -e $dist
    #     echo $dist already exists, skiped
    # else
    #     ensure_dir (dirname $dist)
    #     echo link $dist to $src...
    #     ln -rs $src $dist
    # end
    test_not_exist $dist; or return

    ensure_dir (dirname $dist)
    check ln -rs $src $dist
end

function vimrc
    ensure_dir ~/tmp/vimundo
    ensure_dir ~/tmp/vimbackup
    try_link $PWD/vimrc/vimrc ~/.vim/vimrc
end

function nvim_init
    ensure_dir ~/.local/share/nvim/undo
    try_link $PWD/vimrc/vimrc ~/.config/nvim/init.vim
end

function vim_plug
    set path ~/.vim/autoload/plug.vim
    test_not_exist $path; or return
    check curl -fLo $path --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
end

function vim_plugin
    vimrc
    vim_plug
    try_link $PWD/vimrc/plugin.vim ~/.vim/plugin.vim
    # echo Install Vim plugins...
    check 'vim -c \'execute "PlugInstall" | qa\''
end

function nvim_plug
    set path ~/.local/share/nvim/site/autoload/plug.vim
    test_not_exist $path; or return
    check curl -fLo $path --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
end

function nvim_plugin
    nvim_init
    nvim_plug
    try_link $PWD/vimrc/plugin.vim ~/.vim/plugin.vim
    # echo Install Vim plugins...
    check 'nvim -c \'execute "PlugInstall" | qa\''
end

function oh_my_zsh
    set zpath ~/.antigen
    ensure_dir $zpath/antigen
    check git clone https://github.com/zsh-users/antigen.git $zpath/antigen/
end

function zshrc
    oh_my_zsh
    check ln -rs $PWD/zshrc ~/.zshrc
end

function config.fish
    try_link $PWD/config.fish ~/.config/fish/config.fish
end

function fisherman
    config.fish
    if type -q fisher
        echo command fisher exists, skiped
    else
        echo getting fisherman...
        curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
    end
end

function git_config
    git config --global credential.helper cache
end

function tmux
    set path ~/.tmux/plugins/tpm
    test_not_exist $path; and check git clone https://github.com/tmux-plugins/tpm $path
    check ln -rs $PWD/tmux.conf ~/.tmux.conf
end

set cmds vimrc vim_plug vim_plugin \
         nvim_init nvim_plug nvim_plugin \
         oh_my_zsh zshrc \
         config.fish fisherman \
         git_config

complete -x -c setup -a "$cmds"

for cmd in $argv
    switch $cmd
        case vimrc
            vimrc
        case vim_plug
            vim_plug
        case nvim_init
            nvim_init
        case vim_plugin
            vim_plugin
        case nvim_plugin
            nvim_plugin
        case oh_my_zsh
            oh_my_zsh
        case zshrc
            zshrc
        case config.fish
            config.fish
        case fisherman
            fisherman
        case git_config
            git_config
        case tmux
            tmux
        case '*'
            echo "The command doesn't exist"
            exit 1
    end
end
