#!/usr/bin/fish
#make -f install.mk $argv

function ensure_dir
    set dir $argv[1]
    if not test -e $dir
        echo "$dir don't exist, creat it"
        mkdir -p $dir
    end
end

function try_link
    set src $argv[1]
    set dist $argv[2]
    if test -e $dist
        echo $dist already exists, skiped
    else
        ensure_dir (dirname $dist)
        echo link $dist to $src...
        ln -s $src $dist
    end
end

function vimrc
    ensure_dir ~/tmp/vimundo
    ensure_dir ~/tmp/vimbackup
    try_link $PWD/vimrc/vimrc ~/.vim/vimrc
end

function vundle
    set vpath ~/.vim/bundle/Vundle.vim
    if test -e $vpath
        echo $vpath already exists, skiped
    else
        echo Install Vundle...
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    end
end

function vim_plugin
    vimrc
    vundle
    try_link $PWD/vimrc/plugin.vim ~/.vim/plugin.vim
    echo Install Vim plugins...
    vim -c 'execute "PluginInstall" | qa'
end

function git_config
    git config credential.helper cache
end

for cmd in $argv
    switch $cmd
        case "vimrc"
            vimrc
        case "vundle"
            vundle
        case "vim_plugin"
            vim_plugin
        case "git_config"
            git_config
        case '*'
            echo something bad happend
            exit 1
    end
end
